import { describe, expect, it } from 'vitest'
import { aiGeneratedRule } from './ai-generated'
import type { AccountFeatureBundle } from '../types'

function makeBundle(
  accountOverrides: Partial<AccountFeatureBundle['account']>,
  recentTweets: AccountFeatureBundle['recentTweets'] = [],
): AccountFeatureBundle {
  return {
    account: {
      id: '1',
      screenName: 'x',
      displayName: 'X',
      bio: null,
      followersCount: 0,
      followingCount: 0,
      tweetCount: 0,
      accountCreatedAt: new Date(),
      isBlueVerified: false,
      verifiedType: null,
      ...accountOverrides,
    },
    recentTweets,
  }
}

describe('aiGeneratedRule', () => {
  it('is true for a bio that self-declares AI-generated content', () => {
    const result = aiGeneratedRule.evaluate(
      makeBundle({ bio: 'AI生成してます。登場人物はすべて架空の人物です' }),
    )
    expect(result.value).toBe(true)
    expect(result.confidence).toBeGreaterThan(0)
  })

  it('is true for an English self-declaration', () => {
    const result = aiGeneratedRule.evaluate(makeBundle({ bio: 'All characters generated by AI.' }))
    expect(result.value).toBe(true)
  })

  it('is true for the "生成AI" (generative-AI-first) word order, not just "AI生成"', () => {
    const result = aiGeneratedRule.evaluate(
      makeBundle({ bio: '生成AIと猫への愛50%ずつで構成されています🐾' }),
    )
    expect(result.value).toBe(true)
  })

  it('has higher confidence when tweet text also matches AI-boilerplate phrasing', () => {
    const withoutCorroboration = aiGeneratedRule.evaluate(makeBundle({ bio: 'AI生成してます' }, []))
    const withCorroboration = aiGeneratedRule.evaluate(
      makeBundle({ bio: 'AI生成してます' }, [
        {
          id: 't0',
          fullText: "As an AI language model, here is today's generated story.",
          createdAt: new Date(),
          retweetCount: 0,
          likeCount: 0,
          isReply: false,
          isRetweet: false,
          isPromoted: false,
          isPaidPromotion: false,
        },
      ]),
    )
    expect(withCorroboration.confidence).toBeGreaterThan(withoutCorroboration.confidence)
  })

  it('is false when the bio has no AI-generation declaration', () => {
    const result = aiGeneratedRule.evaluate(
      makeBundle({ bio: 'Full stack dev | Open for freelance work' }),
    )
    expect(result.value).toBe(false)
  })

  it('is false for a bio that explicitly denies using AI generation ("しません")', () => {
    const result = aiGeneratedRule.evaluate(
      makeBundle({
        bio: '写真はすべて自分で撮影・編集しています。一切AI生成はしません。',
      }),
    )
    expect(result.value).toBe(false)
  })

  it('is false for an English bio that denies using AI generation', () => {
    const result = aiGeneratedRule.evaluate(
      makeBundle({ bio: 'All art is hand-drawn. Not AI-generated, never will be.' }),
    )
    expect(result.value).toBe(false)
  })

  it('is false for a regulation-advocacy bio that mentions generative AI as a policy topic, not a self-declaration', () => {
    const result = aiGeneratedRule.evaluate(
      makeBundle({ bio: '生成AI規制派としての意見用アカウント' }),
    )
    expect(result.value).toBe(false)
  })

  it('is false for an official media account reporting on generative AI, not posting it', () => {
    const result = aiGeneratedRule.evaluate(
      makeBundle({
        bio: 'AI 専門メディアの公式アカウントです。生成AIを中心に関連情報をお届けします。記事の配信は自動更新botが行います。',
      }),
    )
    expect(result.value).toBe(false)
  })

  it('is false for a researcher/professor bio that mentions generative AI via a book title, not a self-declaration', () => {
    const result = aiGeneratedRule.evaluate(
      makeBundle({
        bio: '人工知能の研究者 / 大学客員教授 / 著書『生成AI入門』など',
      }),
    )
    expect(result.value).toBe(false)
  })

  it('is false for a bio that lists generative AI as just one of several hobbies followed, not a self-declaration', () => {
    const result = aiGeneratedRule.evaluate(
      makeBundle({
        bio: '競馬好きの一般人です。その他は生成AI遊びとかアニメとかが好きです',
      }),
    )
    expect(result.value).toBe(false)
  })

  it('is false for a local-government liaison bio that mentions gathering/utilizing generative AI info professionally', () => {
    const result = aiGeneratedRule.evaluate(
      makeBundle({
        bio: '自治体と連携して地域社会の活性化に取り組んでいます。生成AIなどの先端技術の情報収集や実活用も合わせて進めています。',
      }),
    )
    expect(result.value).toBe(false)
  })

  it('is false for a bio that denies AI generation using the "NG" prohibition marker', () => {
    const result = aiGeneratedRule.evaluate(
      makeBundle({ bio: '手描きイラスト専門。AI生成NGです。' }),
    )
    expect(result.value).toBe(false)
  })

  it('is false for a bio that denies AI generation using a prohibition emoji placed before the term', () => {
    const result = aiGeneratedRule.evaluate(
      makeBundle({ bio: '🚫AI生成・無断転載は厳禁です。全て自作イラストです。' }),
    )
    expect(result.value).toBe(false)
  })

  it('is false for an investment/stock bio that mentions generative-AI stocks as a market topic, not a self-declaration', () => {
    const result = aiGeneratedRule.evaluate(
      makeBundle({ bio: '半導体・生成AI関連銘柄を中心に投資しています。日々の値動きを記録。' }),
    )
    expect(result.value).toBe(false)
  })

  it('is false for a seminar/advocacy bio using "推進派"/"セミナー" institutional wording', () => {
    const result = aiGeneratedRule.evaluate(
      makeBundle({ bio: '生成AI活用推進派。企業向けセミナー講師をしています。' }),
    )
    expect(result.value).toBe(false)
  })

  it('is still true for an institutional-sounding bio that also explicitly declares its own posted images are AI-generated', () => {
    const result = aiGeneratedRule.evaluate(
      makeBundle({
        bio: 'AI研究者として活動する傍ら、趣味垢です。画像はAI生成のものがあります。お仕事の連絡はDMまで。',
      }),
    )
    expect(result.value).toBe(true)
  })

  it.each([
    ['a plain opposition slogan', '創作アカウント 戦争反対🕊️差別反対🕊️生成AI反対🕊️'],
    ['the "反生成AI" prefix form', '成人/創作/反生成AI/戦争反対/差別反対'],
    ['the #NOMORE無断生成AI campaign tag', '歴史と散歩が好きです。 #NOMORE無断生成AI'],
    ['a dislike statement', 'イラストが好きな人です。生成AI嫌いなので前に出てこないでね。'],
    [
      'a refusal to permit AI use',
      '生成AIは完全オプトイン以外いっさい認めません 無断でAI学習させないで',
    ],
    [
      'an AI-training refusal placed next to the term',
      '旅の記録を残しています。画像本文転載･生成AI学習お断り 連絡はDMへ',
    ],
    [
      'a non-use declaration later in the bio than the first mention',
      '猫と暮らしています。⚠️生成AI利用・無断編集・無断転載お断り 投稿/画像はすべて【生成AI不使用】です',
    ],
  ])('is false for a bio that opposes generative AI via %s', (_label, bio) => {
    expect(aiGeneratedRule.evaluate(makeBundle({ bio })).value).toBe(false)
  })

  // The opposition check must stay narrow: genuine AI creators very commonly forbid
  // reposting or training on their output in the same breath as declaring their own use.
  it.each([
    [
      'a repost refusal aimed at a different object further along the bio',
      '最近はAI生成でイラストも描いていますが、無断転載はお断りします。',
    ],
    [
      'a bare training/repost prohibition',
      '生成AIでファンタジー系のイラストを中心に作っています ⚠️無断での加工・転載・学習禁止です⚠️',
    ],
  ])('is still true for an AI creator whose bio also carries %s', (_label, bio) => {
    expect(aiGeneratedRule.evaluate(makeBundle({ bio })).value).toBe(true)
  })

  it.each([
    [
      'work-efficiency framing',
      '猫とインドカレーとランニングが好き、生成AIで効率化、英語学習／投資',
    ],
    [
      'business-improvement framing',
      '建設業15年以上。Googleスプレッドシート・生成AI・GASで業務改善。',
    ],
    [
      'an interest statement using "関心"',
      '昼の仕事はデータアナリスト/ 最近の関心は生成AI(LLM)/ Like:音楽, 3DCG',
    ],
    ['topic-watching framing', '会社員。生成AIによる著作権問題と犯罪、政治等ウォチ。ねこ好き。'],
  ])('is false for a bio that mentions generative AI via %s', (_label, bio) => {
    expect(aiGeneratedRule.evaluate(makeBundle({ bio })).value).toBe(false)
  })

  it('is false for a bio that blocks accounts posting AI-generated content, not declaring its own', () => {
    const result = aiGeneratedRule.evaluate(
      makeBundle({
        bio: 'クソリプとスパムは即報告、ブロ。過度に差別発言＆RTする人もリムブロ。AI生成ブロ。',
      }),
    )
    expect(result.value).toBe(false)
  })

  it.each([
    [
      'a follow-back refusal aimed at other AI users',
      '※生成AI利用してる方、基本フォロバしてません。V界隈を俯瞰で見るオタク。',
    ],
    [
      'a block policy aimed at other AI users phrased with "使っている方"',
      '手描きイラスト専門の趣味垢。AI生成使っている方はご遠慮ください。',
    ],
  ])('is false for a bio describing a policy toward other accounts via %s', (_label, bio) => {
    expect(aiGeneratedRule.evaluate(makeBundle({ bio })).value).toBe(false)
  })
})
